language: bash
sudo: false
osx_image: xcode9

services:
- docker

os:
- linux
- osx

before_install:

install:

script:
- . ./install.sh
- set -e
- echo $SMING_HOME
- echo $ESP_HOME
- cd $SMING_HOME
- make test

- "docker run -i -v \"${PWD}:/MyProgram\" toopher/centos-i386:centos6 /bin/bash -c \"linux32 --32bit i386 . /MyProgram/install.sh\""
