language: bash

os:
- linux
  sudo: false
  dist: trusty
- osx

before_install:

install:

script:
- . ./install.sh
- set -e
- cd $SMING_HOME/../samples/Basic_Blink
- make V=1
- cd $SMING_HOME/../samples/Basic_Ssl
- make V=1
