language: bash
sudo: false

os:
- linux
- osx

before_install:

install:

script:
- . ./install.sh
- set -e
- echo $SMING_HOME
- echo $ESP_HOME
- ls $SMING_HOME/../samples/Basic_Blink"
- cd $SMING_HOME/../samples/Basic_Blink
- echo "Building Blink sample"
- make
- echo "Building SSL sample"
- cd $SMING_HOME/../samples/Basic_Ssl
- make
