sudo: false
language: bash

os:
- linux
- osx
env: 
  matrix:
  - VERSION=3.5.1
addons:
  apt:
    packages:
    - bash

before_install:

install:

script:
- set -e
- . ./install.sh
- cd $SMING_HOME/../samples/Basic_Blink
- make V=1
- cd $SMING_HOME/../samples/Basic_Ssl
- make V=1
