language: bash
sudo: false

notifications:
  email: false

os:
- linux
- osx

env:
  - ARCH=x86_64
  - ARCH=i686

matrix:
  exclude:
    - os: osx
      env: ARCH=i686

script:
  - set -e
  - chmod 777 install.sh
  - 'if [ "$ARCH" = "i686" ]; then
    docker run -i -v "${PWD}:/MyProgram" i386/ubuntu:16.04 /bin/bash -c "linux32 --32bit i386 apt update; linux32 --32bit i386 apt install -y wget unzip python build-essential; linux32 --32bit i386 /MyProgram/install.sh";
    travis_terminate 0;
    fi'
  - ./install.sh
  - . Sming/setenv.sh
  - cd $SMING_HOME
  - make test
