sudo: false
language: c

os:
- linux
- osx
env: 
  matrix:
  - VERSION=3.5.1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bsdtar
    - doxygen
    - bash
install:
script:
- set -e
- bash install.sh
- cd $SMING_HOME/../samples/Basic_Blink
- make

