sudo: false
os:
- linux
env: 
  matrix:
  - VERSION=3.5.1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bsdtar
    - doxygen
install:
script:
- sh ./install.sh
- cd $SMING_HOME/../samples/Basic_Blink
- make

