language: bash
sudo: false

os:
- linux
- osx

before_install:

install:

script:
- . ./install.sh
- set -e
- echo $SMING_HOME
- echo $ESP_HOME
- cd $SMING_HOME/../samples/Basic_Blink
- make V=1
- cd $SMING_HOME/../samples/Basic_Ssl
- make V=1
