os: Windows Server 2012 R2
init: 
  - git config --global core.autocrlf input
    
environment:
  global:
    BASH: C:\cygwin\bin\bash
    CYG_SETUP: C:\cygwin\setup-x86

  matrix:
    - build_platform: "x86"
    - build_platform: "x64"

install:
  - '%CYG_SETUP% -qP wget unzip'

build_script:
  - '%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && ./install.sh"'
  - '%BASH% -lc "echo export SMING_HOME=$APPVEYOR_BUILD_FOLDER/Sming/Sming | sed 's/\\/\//g'> ~/set_sming_vars'
  - '%BASH% -lc "echo export ESP_HOME=$APPVEYOR_BUILD_FOLDER/Sming/esp-toolkit | sed 's/\\/\//g' >> ~/set_sming_vars"'
  - '%BASH% -lc ". ~/set_sming_vars && cd $SMING_HOME/../samples/Basic_Blink && make V=1"'
  - '%BASH% -lc ". ~/set_sming_vars && cd $SMING_HOME/../samples/Basic_Ssl && make V=1"'
