os: Windows Server 2012 R2

only_commits:
  files:
    - install.sh

init:
  - git config --global core.autocrlf input
    
environment:
  global:
    BASH: C:\cygwin\bin\bash
    CYG_SETUP: C:\cygwin\setup-x86

  matrix:
    - build_platform: "x86"
    - build_platform: "x64"

install:
  - '%CYG_SETUP% -qP wget unzip'

build_script:
  - '%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && pwd"'
  - '%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && ./install.sh"'
  - '%BASH% -lc ". $APPVEYOR_BUILD_FOLDER/Sming/setenv && cd $SMING_HOME && make test"'
