os: Windows Server 2012 R2
init: 
  - git config --global core.autocrlf input
    
environment:
  global:
    BASH: C:\cygwin\bin\bash
    CYG_SETUP: C:\cygwin\setup-x86

  matrix:
    - build_platform: "x86"
    - build_platform: "x64"

install:
  - '%CYG_SETUP% -qP wget unzip'

build_script:
  - '%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && ./install.sh"'
  - '%BASH% -lc "echo SMING_HOME=$APPVEYOR_BUILD_FOLDER/Sming/Sming >> /etc/environment"'
  - '%BASH% -lc "echo ESP_HOME=$APPVEYOR_BUILD_FOLDER/Sming/esp-toolkit >> /etc/environment"'
  - '%BASH% -lc "echo $SMING_HOME"'
  - '%BASH% -lc "cd $SMING_HOME/../samples/Basic_Blink && make V=1"'
  - '%BASH% -lc "cd $SMING_HOME/../samples/Basic_Ssl && make V=1"'
