os: Windows Server 2012 R2
init: 
  - git config --global core.autocrlf input
    
environment:
  global:
    BASH: C:\cygwin\bin\bash
    CYG_SETUP: C:\cygwin\setup-x86

  matrix:
    - build_platform: "x86"
    - build_platform: "x64"

install:
  - '%CYG_SETUP% -qP wget unzip'

build_script:
  - '%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && pwd"'
  - '%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && ./install.sh"'
  - '%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && echo export SMING_HOME=`pwd`/Sming/Sming > ~/set_sming_vars'
  - '%BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && echo export ESP_HOME=`pwd`/Sming/esp-toolkit >> ~/set_sming_vars'
  - '%BASH% -lc ". ~/set_sming_vars && cd $SMING_HOME && make test"'
